[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/"
  weight = 20

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 25

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 40
